<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delete_specility</name>
   <tag></tag>
   <elementGuidId>d1bb5996-4141-4c5b-bbc9-73f72362dd4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='specialitytable']//tbody[@id='specialitydata']//tr[last()-1]//td[2]/following-sibling::td[3]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
